- src/components/atoms/InputRadio.tsx
- src/components/atoms/InputText.tsx
- src/components/atoms/Message.tsx
- src/components/atoms/Next.tsx
- src/components/atoms/Previous.tsx
- src/utils/mixins.ts
- src/utils/theme.ts
> Issue 14/design inputs

- src/components/atoms/InputRadio.tsx
- src/components/atoms/InputText.tsx
- src/components/atoms/Message.tsx
- src/components/atoms/Next.tsx
- src/components/atoms/Previous.tsx
- src/components/molecules/DialogNavigation.tsx
- src/components/molecules/EyesAnimation.tsx
- src/components/molecules/Form.tsx
- src/components/organisms/Dialog.tsx
- src/components/organisms/Game.tsx
- src/layouts/index.tsx
- src/pages/index.tsx
- src/utils/story.ts
> Issue 30/add intro fix story

- src/components/atoms/CharacterTitle.tsx
- src/components/atoms/InputText.tsx
- src/components/atoms/Next.tsx
- src/components/molecules/Form.tsx
- src/components/organisms/Dialog.tsx
- src/utils/functions.ts
- src/utils/localKeys.ts
- src/utils/story.ts
> Issue 37/fix breaking box

- src/components/atoms/Next.tsx
- src/components/atoms/Previous.tsx
- src/components/molecules/DialogNavigation.tsx
- src/components/organisms/Dialog.tsx
This closes #41 and closes #42
> Prevent Next if formValue isn't filled out

- package.json
- src/utils/functions.ts
- src/utils/story.ts
> Issue 44/fix answer casing

- src/components/atoms/AchievementCommandLine.tsx
- src/components/atoms/AchievementPlaceholder.tsx
- src/components/atoms/Avatar.tsx
- src/components/atoms/CodeCash.tsx
- src/components/atoms/IconCoin.tsx
- src/components/atoms/IconFire.tsx
- src/components/atoms/IconStar.tsx
- src/components/atoms/Streak.tsx
- src/components/molecules/Achievements.tsx
- src/components/molecules/DailyChallenges.tsx
- src/components/molecules/DeveloperProgress.tsx
- src/components/molecules/ProfileHeader.tsx
- src/components/molecules/ProfileHeaderAvatarWithName.tsx
- src/components/molecules/ProfileStatBars.tsx
- src/components/molecules/XPBar.tsx
- src/components/organisms/Dashboard.tsx
- src/components/organisms/Profile.tsx
- src/pages/index.tsx
- src/utils/theme.ts
> Issue 46/design dashboard

- src/components/molecules/Map.tsx
- src/components/organisms/Dashboard.tsx
> Add Map to Dashboard

- src/components/molecules/Map.tsx
- src/components/organisms/Dashboard.tsx
Fixes #62 
Not perfect, but at least now everything looks a little better.
> Fix Map look on mobile

- __mocks__/gatsby.js
- __tests__/component/CharacterTitle.test.js
- jest-preprocess.js
- jest.config.js
- loadershim.js
- package.json
- setup-test-env.js
- src/components/atoms/CharacterTitle.tsx
- yarn.lock
> Issue 61/add unit testing

- src/components/atoms/Arrow.tsx
- src/components/atoms/CharacterTitle.tsx
- src/components/atoms/InputRadio.tsx
- src/components/atoms/InputText.tsx
- src/components/atoms/Message.tsx
- src/components/atoms/Next.tsx
- src/components/atoms/Previous.tsx
- src/components/organisms/Dialog.tsx
- src/utils/theme.ts
> Issue 60/add all theme colors

- src/components/atoms/Chalkboard.tsx
- src/components/molecules/Overlay.tsx
- src/components/organisms/App.tsx
- src/components/organisms/Dashboard.tsx
- src/components/organisms/Game.tsx
> Issue 77/add chalkboard

- gatsby-browser.js
- package.json
- src/components/organisms/Dashboard.tsx
- src/utils/apiCalls.ts
- yarn.lock
> Issue 53/graphql check repo

- src/components/atoms/Streak.tsx
- src/components/organisms/App.tsx
- src/components/organisms/Dashboard.tsx
- src/utils/apiCalls.ts
- src/utils/functions.ts
Fixes #93 
Wait until it's been tested tomorrow.
> [WIP] Issue 93/add logic to track streak

- gatsby-browser.js
- src/components/organisms/App.tsx
- src/utils/apiCalls.ts
> Issue 93/add streak logic

- src/components/atoms/MapContainer.tsx
- src/components/organisms/Dashboard.tsx
> Issue 100/comment out sidebar

- src/components/molecules/Overlay.tsx
> Redesign Exit Button

- src/components/molecules/Overlay.tsx
> Fix design for view courses page

- src/components/molecules/Overlay.tsx
- src/utils/functions.ts
> Issue 92/save progress logic

- src/components/atoms/MobileMessage.tsx
- src/components/organisms/App.tsx
- src/pages/index.tsx
- src/utils/functions.ts
> Issue 104/add note mobile

- src/components/molecules/Overlay.tsx
- src/utils/functions.ts
- src/utils/story.ts
> Issue 102/add images

- src/components/molecules/Overlay.tsx
> Fix Exit to show 'View Courses' if clicking from Game

- src/components/atoms/MapContainer.tsx
> Change Map dimensions based on window

- src/components/atoms/Message.tsx
> Issue 118/cant type input

- src/components/atoms/InputRadio.tsx
- src/components/molecules/Form.tsx
- src/components/molecules/Overlay.tsx
- src/components/organisms/Dialog.tsx
- src/components/organisms/Game.tsx
- src/lesons/story.ts
- src/pages/dashboard.tsx
- src/utils/functions.ts
> Refactor story to be lesson prop on Game
